name: Flask CI

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run the Docker container
        run: |
          docker build -t my-flask-app .
          docker run -d -p 5000:5000 my-flask-app
